<?php

use Drupal\Core\Datetime\DrupalDateTime;

/**
 * @file
 * Contains duet_date_picker.module.
 */

/**
 * Implements hook_theme().
 */
function duet_date_picker_theme($existing, $type, $theme, $path) {
  return [
    'duet_date_picker' => [
      'base hook' => 'datetime_default',
      'render element' => 'date',
    ],
    'duet_daterange_picker' => [
      'base hook' => 'daterange_default',
      'render element' => 'date',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function duet_date_picker_preprocess_duet_date_picker(&$variables) {
  // Format the default value in a way the date picker will accept.
  $formatted_default_date = '';
  if (!empty($variables['date']) and !empty($variables['date']['#default_value'])) {
    $default_value = $variables['date']['#default_value'];
    if ($default_value instanceof DrupalDateTime) {
      $formatted_default_date = $default_value->format('Y-m-d');
    }
  }
  $variables['make_required'] = ($variables['date']['#required'] == TRUE) ? 'true' : 'false';
  $variables['formatted_default_date'] = $formatted_default_date;
  // Pass today's date as a minimum date if the settings disallow past dates.
  if ($variables['date']['settings']['no_past_dates']) {
    $variables['min_date'] = date('Y-m-d');
  }
}
