<?php

/**
 * @file
 * Contains duet_date_picker.module.
 */

/**
 * Implements hook_theme().
 */
function duet_date_picker_theme($existing, $type, $theme, $path) {
  return [
    'duet_date_picker' => [
      'base hook' => 'datetime_default',
      'render element' => 'date',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function duet_date_picker_preprocess_duet_date_picker(&$variables) {
  // Do any preprocessing here for duet date picker template.
}
